export const Books = [
    {
        isbn:"9781593279509",
        title:"Eloquent JavaScript, Third Edition",
        subtitle:"A Modern Introduction to Programming",
        category: "programming",
        author:"Marijn Haverbeke",
        publishedDate:"2018-12-04T00:00:00.000Z",
        publisher:"No Starch Press",
        pages:472,
        description:"JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
        website:"http://eloquentjavascript.net/",
        image:"https://eloquentjavascript.net/img/cover.jpg"
    },
    {
        isbn:"9781491943533",
        title:"Practical Modern JavaScript",
        subtitle:"Dive into ES6 and the Future of JavaScript",
        category: "programming",
        author:"Nicolás Bevacqua",
        publishedDate:"2017-07-16",
        publisher:"O'Reilly Media",
        pages:334,
        description:"To get the most out of modern JavaScript, you need learn the latest features of its parent specification, ECMAScript 6 (ES6). This book provides a highly practical look at ES6, without getting lost in the specification or its implementation details.",
        website:"https://github.com/mjavascript/practical-modern-javascript",
        image:"https://learning.oreilly.com/library/cover/9781491943526/250w/"
    },
    {
        isbn:"9781593277574",
        title:"Understanding ECMAScript 6",
        subtitle:"The Definitive Guide for JavaScript Developers",
        category: "programming",
        author:"Nicholas C. Zakas",
        publishedDate:"2016-09-03",
        publisher:"No Starch Press",
        pages:352,
        description:"ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript.",
        website:"https://leanpub.com/understandinges6/read",
        image:"https://d2sofvawe08yqg.cloudfront.net/understandinges6/s_hero?1620418785"
    },
    {
        isbn:"9781449365035",
        title:"Speaking JavaScript",
        subtitle:"An In-Depth Guide for Programmers",
        category: "programming",
        author:"Axel Rauschmayer",
        publishedDate:"2014-04-08",
        publisher:"O'Reilly Media",
        pages:460,
        description:"Like it or not, JavaScript is everywhere these days -from browser to server to mobile- and now you, too, need to learn the language or dive deeper than you have. This concise book guides you into and through JavaScript, written by a veteran programmer who once found himself in the same position.",
        website:"http://speakingjs.com/",
        image:"http://speakingjs.com/speakingjs_cover_large.jpg"
    },
    {
        isbn:"9781449331818",
        title:"Learning JavaScript Design Patterns",
        subtitle:"A JavaScript and jQuery Developer's Guide",
        category: "programming",
        author:"Addy Osmani",
        publishedDate:"2012-08-30",
        publisher:"O'Reilly Media",
        pages:254,
        description:"With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
        website:"http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/",
        image:"https://m.media-amazon.com/images/I/81LpyFBbo8L._SL1500_.jpg"
    },
    {
        isbn:"9798602477429",
        title:"You Don't Know JS Yet",
        subtitle:"Get Started",
        category: "programming",
        author:"Kyle Simpson",
        publishedDate:"2020-01-28",
        publisher:"Independently published",
        pages:143,
        description:"The worldwide best selling You Don't Know JS book series is back for a 2nd edition: You Don't Know JS Yet. All 6 books are brand new, rewritten to cover all sides of JS for 2020 and beyond.",
        website:"https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/get-started",
        image:"https://m.media-amazon.com/images/I/410f-bUBR3L.jpg"
    },
    {
        isbn:"9781484200766",
        title:"Pro Git",
        subtitle:"Everything you neeed to know about Git",
        category: "programming",
        author:"Scott Chacon and Ben Straub",
        publishedDate:"2014-11-18",
        publisher:"Apress; 2nd edition",
        pages:458,
        description:"Pro Git (Second Edition) is your fully-updated guide to Git and its usage in the modern world. Git has come a long way since it was first developed by Linus Torvalds for Linux kernel development. It has taken the open source world by storm since its inception in 2005, and this book teaches you how to use it like a pro.",
        website:"https://git-scm.com/book/en/v2",
        image:"https://git-scm.com/images/progit2.png"
    },
    {
        isbn:"9781484242216",
        title:"Rethinking Productivity in Software Engineering",
        subtitle:" ",
        category: "programming",
        author:"Caitlin Sadowski, Thomas Zimmermann",
        publishedDate:"2019-05-11",
        publisher:"Apress",
        pages:310,
        description:"Get the most out of this foundational reference and improve the productivity of your software teams. This open access book collects the wisdom of the 2017 \"Dagstuhl\" seminar on productivity in software engineering, a meeting of community leaders, who came together with the goal of rethinking traditional definitions and measures of productivity.",
        website:"https://doi.org/10.1007/978-1-4842-4221-6",
        image:"https://www.dbooks.org/img/books/1484242211.jpg"
    },
    { 
        isbn: "9780262043793",
        title: "Introduction to Machine Learning",
        subtitle: "A Probabilistic Perspective",
        category: "programming",
        author: "Kevin P. Murphy",
        publishedDate: "2012-06-15",
        publisher: "MIT Press", pages: 740,
        description: "This book provides a comprehensive introduction to the field of machine learning, covering both the theory and practice of the most important algorithms.",
        website: "https://mitpress.mit.edu/books/introduction-machine-learning",
        image: "https://product.hstatic.net/200000211451/product/cover1_0a64dc26d4dd424b8a91d645c7971e7e_master.jpeg"
    },
    { 
        isbn: "9780262035613",
        title: "Deep Learning",
        subtitle: "A Practitioner's Approach",
        category: "programming",
        author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        publishedDate: "2016-11-18", publisher: "MIT Press",
        pages: 775,
        description: "Deep Learning is a comprehensive guide to the field, covering both the theory and practice of deep learning algorithms.",
        website: "https://mitpress.mit.edu/books/deep-learning",
        image: "https://th.bing.com/th/id/OIP.WCYIvVKFCECYZt_ubqvX-wHaJv?rs=1&pid=ImgDetMain"
    },
    { 
        isbn: "9780262510875",
        title: "Structure and Interpretation of Computer Programs",
        subtitle: "Building on the Legacy of SICP",
        category: "programming",
        author: "Harold Abelson, Gerald Jay Sussman, Julie Sussman",
        publishedDate: "2022-04-12",
        publisher: "MIT Press",
        pages: 600,
        description: "This book provides a deep understanding of the principles of computer programming, using Scheme as the language of instruction.",
        website: "https://mitpress.mit.edu/books/structure-interpretation-computer-programs",
        image: "https://th.bing.com/th/id/OIP._6TYAd1q3_2Ewrd3oIfuugHaKr?w=1200&h=1730&rs=1&pid=ImgDetMain"
    },
    { 
        isbn: "9780262033848",
        title: "Introduction to Algorithms",
        subtitle: "Third Edition",
        category: "programming",
        author: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
        publishedDate: "2022-04-05",
        publisher: "MIT Press",
        pages: 1000,
        description: "This book provides a comprehensive introduction to the field of algorithms, covering both the theory and practice of the most important algorithms.",
        website: "https://mitpress.mit.edu/books/introduction-algorithms",
        image: "https://th.bing.com/th/id/OIP.3YBaTEDl9yVQt3-ZSPZ-7gAAAA?rs=1&pid=ImgDetMain"
    },
    { 
        isbn: "9780262033849",
        title: "Dune",
        subtitle: "A Science Fiction Novel",
        category: "sci-fi",
        author: "Frank Herbert",
        publishedDate: "1965-08-01",
        publisher: "Chilton Books",
        pages: 412,
        description: "Set in the distant future amidst a huge interstellar empire...",
        website: "https://dunenovels.com/",
        image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEitSGiJNS7jKFma416_EHY0P_5Oo9uZQvYJre1LauONl4Kh_T7h841WNGtl3OrTSmPuSgIID46iQkvIOuj-BgDCelrK3negswy-BnLqcVOvxPovzoEf11Pu29AfgIIRLKPwo3zWu_3Cyls/s400/Dune_Novel_19.png"
    },
    {
        isbn: "9780743273565",
        title: "The Great Gatsby",
        category: "fiction",
        subtitle: "",
        author: "F. Scott Fitzgerald",
        publishedDate: "1925-04-10",
        publisher: "Charles Scribner's Sons",
        pages: 218,
        description: "The novel chronicles an era that Fitzgerald himself dubbed the 'Jazz Age'...", website: "https://www.fsgbooks.com/books/the-great-gatsby/",
        image: "https://m.media-amazon.com/images/I/81af+MCATTL.jpg"
    },
    {
        isbn: "9780679783268",
        title: "Pride and Prejudice",
        category: "fiction",
        subtitle: "",
        author: "Jane Austen",
        publishedDate: "1813-01-28",
        publisher: "T. Egerton, Whitehall",
        pages: 432,
        description: "A romantic novel of manners that depicts the British Regency era.",
        website: "https://m.media-amazon.com/images/I/81zRJPWxoHL.jpg",
        image: "https://th.bing.com/th/id/OIP.BFphXSy0Q1hijrcFhAI28QHaLa?rs=1&pid=ImgDetMain.jpg"
    },
    {
        isbn: "9780061120084",
        title: "To Kill a Mockingbird",
        category: "fiction",
        subtitle: "",
        author: "Harper Lee",
        publishedDate: "1960-07-11",
        publisher: "J.B. Lippincott & Co.",
        pages: 281,
        description: "A novel about the serious issues of rape and racial inequality.",
        website: "https://m.media-amazon.com/images/I/71FXfPSF3wL.jpg",
        image: "https://th.bing.com/th/id/OIP.W1ngiF2AkQaO78CY9yC1HQHaLd?rs=1&pid=ImgDetMain.jpg"
    },
    { 
        isbn: "9780451524935",
        title: "1984",
        category: "fiction",
        subtitle: "",
        author: "George Orwell",
        publishedDate: "1949-06-08",
        publisher: "Secker & Warburg",
        pages: 328,
        description: "A dystopian social science fiction novel and cautionary tale.",
        website: "https://m.media-amazon.com/images/I/91SZSW8qSsL.jpg",
        image: "https://m.media-amazon.com/images/I/91SZSW8qSsL.jpg"
    },
    { 
        isbn: "9780316769488",
        title: "The Catcher in the Rye",
        category: "fiction",
        subtitle: "",
        author: "J.D. Salinger",
        publishedDate: "1951-07-16",
        publisher: "Little, Brown and Company",
        pages: 277,
        description: "A story about teenage rebellion and angst.",
        website: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
        image: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg"
    },
    { 
        isbn: "9780062316097",
        title: "Sapiens: A Brief History of Humankind",
        category: "non-fiction",
        subtitle: "",
        author: "Yuval Noah Harari",
        publishedDate: "2014-09-04",
        publisher: "Harper",
        pages: 443,
        description: "A book that explores the history of humankind.",
        website: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
        image: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg"
    },
    {
        isbn: "9780399590504",
        title: "Educated",
        category: "non-fiction",
        subtitle: "",
        author: "Tara Westover",
        publishedDate: "2018-02-20",
        publisher: "Random House",
        pages: 334,
        description: "A memoir about growing up in a strict and abusive household in rural Idaho.",
        website: "https://m.media-amazon.com/images/I/81WojUxbbFL.jpg",
        image: "https://m.media-amazon.com/images/I/81WojUxbbFL.jpg"     
    },
    {
        isbn: "9781524763138",
        title: "Becoming",
        category: "non-fiction",
        subtitle: "",
        author: "Michelle Obama",
        publishedDate: "2018-11-13",
        publisher: "Crown Publishing Group",
        pages: 448,
        description: "A memoir by the former First Lady of the United States.",
        website: "https://m.media-amazon.com/images/I/81h2gWPTYJL.jpg",
        image: "https://m.media-amazon.com/images/I/81h2gWPTYJL.jpg" 
    },
    {
        isbn: "9781400052189",
        title: "The Immortal Life of Henrietta Lacks",
        category: "non-fiction",
        subtitle: "",
        author: "Rebecca Skloot",
        publishedDate: "2010-02-02",
        publisher: "Crown",
        pages: 381,
        description: "A book about the life of Henrietta Lacks and the immortal cell line, HeLa.",
        website: "https://m.media-amazon.com/images/I/81y2D8hJ7xL.jpg",
        image: "https://th.bing.com/th/id/OIP.cq0Px6MTppLepZ3_vG7yvQAAAA?rs=1&pid=ImgDetMain.jpg"
    },
    {
        isbn: "9780374533557",
        title: "Thinking, Fast and Slow",
        category: "non-fiction",
        subtitle: "",
        author: "Daniel Kahneman",
        publishedDate: "2011-10-25",
        publisher: "Farrar, Straus and Giroux",
        pages: 499,
        description: "A book that explores the two systems that drive the way we think.", website: "https://m.media-amazon.com/images/I/71pV--jmcEL.jpg",
        image: "https://th.bing.com/th/id/OIP.O4xDiZh6rtXlOCJxy0C7LwHaLY?rs=1&pid=ImgDetMain.jpg"        
    },
    { 
        isbn: "9780441569595",
        title: "Neuromancer",
        category: "sci-fi",
        subtitle: "",
        author: "William Gibson",
        publishedDate: "1984-07-01",
        publisher: "Ace Books",
        pages: 271,
        description: "A novel that tells the story of a washed-up computer hacker hired for one last job.",
        website: "https://m.media-amazon.com/images/I/81J-P4V4S-L.jpg",
        image: "https://th.bing.com/th/id/OIP.LfwWQ9Tz6qFNMr4IK7A-VwHaLV?rs=1&pid=ImgDetMain.jpg"       
    },
    { 
        isbn: "9780553293357",
        title: "Foundation",
        category: "sci-fi",
        subtitle: "",
        author: "Isaac Asimov",
        publishedDate: "1951",
        publisher: "Gnome Press",
        pages: 255,
        description: "A science fiction novel about the collapse and rebirth of a galactic empire.",
        website: "https://m.media-amazon.com/images/I/81aA7hEEykL.jpg",
        image: "https://m.media-amazon.com/images/I/81aA7hEEykL.jpg"   
    },
    { 
        isbn: "9780553380958",
        title: "Snow Crash",
        category: "sci-fi",
        subtitle: "",
        author: "Neal Stephenson",
        publishedDate: "1992-06-01",
        publisher: "Bantam Books",
        pages: 470,
        description: "A cyberpunk novel that explores a near-future America.",
        website: "https://m.media-amazon.com/images/I/91SEF6JXG0L.jpg",
        image: "https://th.bing.com/th/id/OIP.IzaWe6SSyfhSFelSJuT5-wHaLj?rs=1&pid=ImgDetMain.jpg"
    },
    { 
        isbn: "9780441478125",
        title: "The Left Hand of Darkness",
        category: "sci-fi",
        subtitle: "",
        author: "Ursula K. Le Guin",
        publishedDate: "1969",
        publisher: "Ace Books",
        pages: 304,
        description: "A novel that tells the story of a human envoy to a winter world where inhabitants can change gender.",
        website: "https://m.media-amazon.com/images/I/81-349WFhvL.jpg",
        image: "https://th.bing.com/th/id/OIP.lvXmemHqFnhisGt96JFdSwHaLZ?rs=1&pid=ImgDetMain.jpg"          
    },
    { 
        isbn: "9780765382030",
        title: "The Three-Body Problem",
        category: "sci-fi",
        subtitle: "",
        author: "Liu Cixin",
        publishedDate: "2008",
        publisher: "Chongqing Press",
        pages: 302,
        description: "A novel that tells the story of Earth's first contact with an alien civilization.",
        website: "https://m.media-amazon.com/images/I/91TW2ntwwmL.jpg",
        image: "https://th.bing.com/th/id/OIP.VOz8QnlqQdViMr9wzdZa8AAAAA?rs=1&pid=ImgDetMain.jpg"
    }
]